brand/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "brand"

urlpatterns = [
    path("", RedirectView.as_view(url="clothing/")),
    path(
        "p/",
        RedirectView.as_view(url="../clothing/"),
        name="brand_listing_default",
    ),
    path("p/<int:brand_id>/", views.brand_detail, name="brand_detail"),
    path(
        "<str:selected_category>/", views.brand_listing, name="brand_listing"
    ),
]

brand/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower

from utilities.dates import current_india_time


class LowerCaseCharField(models.CharField):
    def get_prep_value(self, value):
        return str(value).lower()


class Brand(models.Model):
    class Location(models.TextChoices):
        INDIA = "IND"
        INTERNATIONAL = "INT"

    class PaymentMode(models.TextChoices):
        PREPAID_ONLY = "PRE", "Prepaid Only"
        BOTH = "BOTH", "Both Prepaid and Payment On Delivery"

    class RefundMode(models.TextChoices):
        REFUND = "RFND", "Can Refund Or Exchange"
        EXCHANGE_ONLY = "EXCH", "No Refund, Exchange Only"
        NA = "NONE", "Neither Refund Nor Exchange"

    class IndicativePricing(models.TextChoices):
        BUDGET_FRIENDLY = "BGT"
        VALUE = "VAL"
        LUXURY = "LUX"

    # Basic
    name = models.CharField(max_length=100)
    company_name = models.CharField(blank=True, max_length=100)
    title = models.CharField(max_length=300)
    description = models.TextField()
    founding_year = models.PositiveIntegerField(
        validators=[MinValueValidator(1500), MaxValueValidator(3000)]
    )
    company_size = models.PositiveIntegerField(
        validators=[MinValueValidator(1)], default=1
    )
    location = models.CharField(max_length=3, choices=Location.choices)

    # Shopping
    offline_presence = models.BooleanField(default=False)
    delivery_days = models.PositiveIntegerField(default=7)
    return_days = models.PositiveIntegerField(default=7)
    payment_mode = models.CharField(
        max_length=4, blank=True, choices=PaymentMode.choices
    )
    refund_mode = models.CharField(
        max_length=4, blank=True, choices=RefundMode.choices
    )
    refund_shipping_included = models.BooleanField(default=False)

    # Communication
    company_address = models.TextField(blank=True)
    website = models.URLField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    email_address = models.EmailField(blank=True)
    instagram_profile = models.URLField(max_length=100, blank=True)
    facebook_profile = models.URLField(max_length=100, blank=True)
    linkedin_profile = models.URLField(max_length=100, blank=True)
    twitter_profile = models.URLField(max_length=100, blank=True)

    # Labels
    indicative_pricing = models.CharField(
        max_length=3, blank=True, choices=IndicativePricing.choices
    )
    made_in_india = models.BooleanField(default=True)
    environment_friendly = models.BooleanField(default=False)
    handcrafted = models.BooleanField(default=False)
    customizable = models.BooleanField(default=False)
    plus_size_available = models.BooleanField(default=False)
    material = models.CharField(max_length=250, blank=True)
    certifications = models.CharField(max_length=250, blank=True)

    # Others
    keywords = models.TextField(blank=True)
    is_claimed = models.BooleanField(default=False)
    user_rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
    )
    brandscanner_rating = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
    )
    page_views = models.PositiveIntegerField(default=0)

    # System internal
    last_updated = models.DateTimeField(default=current_india_time)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class OnlineStore(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        constraints = [
            UniqueConstraint(
                Lower("name"), name="unique_case_insensitive_online_store_name"
            )
        ]


class BrandOnlineStore(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    online_store = models.ForeignKey(OnlineStore, on_delete=models.PROTECT)

    def __str__(self):
        return f"[{self.brand}] {self.online_store}"

    class Meta:
        constraints = [
            UniqueConstraint(
                "brand", "online_store", name="unique_brand_online_store_pair"
            )
        ]


class Person(models.Model):
    class Salutation(models.TextChoices):
        MR = "MR", "Mr."
        MS = "MS", "Ms."
        MRS = "MRS", "Mrs."
        DR = "DR", "Dr."
        PT = "PT", "Pt."

    salutation = models.CharField(max_length=4, choices=Salutation.choices)
    name = models.CharField(max_length=100)
    photo = models.ImageField(
        blank=True,
        upload_to="uploads/%Y/%m/%d/",
        help_text="Upload a display picture for this person.",
    )
    background = models.TextField(
        blank=True,
        help_text="Provide a short backgound information.",
    )
    is_celebrity = models.BooleanField(
        default=False,
        help_text="Is this person is a celebrity?",
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = "people"


class BrandKeyPerson(models.Model):
    class Designation(models.TextChoices):
        FOUNDER = "FR"
        CO_FOUNDER = "CFR"
        DIRECTOR = "DR"
        VICE_PRESIDENT = "VP"

    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)
    designation = models.CharField(max_length=4, choices=Designation.choices)

    def __str__(self):
        return f"[{self.brand.name}] [{self.designation}] {self.person.name}"

    class Meta:
        verbose_name_plural = "key people"


class BrandEndorsement(models.Model):
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, help_text="Select a brand."
    )
    person = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        help_text="Select from existing people.",
    )
    collection_name = models.CharField(
        max_length=50,
        help_text="Provide the product collection name.",
    )

    def __str__(self):
        return (
            f"[{self.brand.name}] [{self.person.name}] {self.collection_name}"
        )


class BrandBestseller(models.Model):
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, help_text="Select a brand."
    )
    collection_name = models.CharField(
        max_length=50,
        help_text="Provide the product collection name.",
    )
    collection_date = models.CharField(
        max_length=50,
        help_text="Provide month and year. Ex: May 2023",
    )

    def __str__(self):
        return f"[{self.brand.name}] {self.collection_name}"


class BrandAsset(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)

    asset = models.FileField(
        upload_to="uploads/%Y/%m/%d/",
        help_text="Select an image that you want to upload.",
    )
    title = models.CharField(
        max_length=100,
        help_text="Provide a title for this image.",
    )

    endorsement = models.ForeignKey(
        BrandEndorsement,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        help_text="Associate with an endorsement, if applicable.",
    )
    bestseller = models.ForeignKey(
        BrandBestseller,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        help_text="Associate with a bestseller, if applicable.",
    )
    sequence = models.PositiveIntegerField(default=1)

    uploaded_at = models.DateTimeField(default=current_india_time)

    def get_absolute_url(self):
        return self.asset.url

    def __str__(self):
        return f"[{self.brand.name}] {self.title}"


class BrandVisual(models.Model):
    brand = models.OneToOneField(
        Brand, on_delete=models.CASCADE, help_text="Select a brand."
    )

    logo = models.ForeignKey(
        BrandAsset,
        on_delete=models.SET_NULL,
        related_name="brand_logo",
        blank=True,
        null=True,
        help_text="Select from existing image assets.",
    )
    cover = models.ForeignKey(
        BrandAsset,
        on_delete=models.SET_NULL,
        related_name="brand_cover",
        blank=True,
        null=True,
        help_text="Select from existing image assets.",
    )

    def get_logo_url(self):
        url = ""
        if self.logo is not None:
            url = self.logo.get_absolute_url()
        return url

    def get_cover_url(self):
        url = ""
        if self.cover is not None:
            url = self.cover.get_absolute_url()
        return url

    def __str__(self):
        return f"Visuals for {self.brand.name}"


class Category(models.Model):
    internal_name = LowerCaseCharField(max_length=15)
    display_name = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.display_name}"

    class Meta:
        verbose_name_plural = "categories"
        constraints = [
            UniqueConstraint(
                Lower("internal_name"),
                name="unique_case_insensitive_category_internal_name",
            ),
            UniqueConstraint(
                Lower("display_name"),
                name="unique_case_insensitive_category_display_name",
            ),
        ]


class Tag(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = LowerCaseCharField(max_length=30)
    value = LowerCaseCharField(max_length=50)
    sequence = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"[{self.category}] {self.name}={self.value}"

    class Meta:
        constraints = [
            UniqueConstraint(
                "category",
                "name",
                "value",

brand/views.py
import copy

from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, render

from brand.models import Brand, Category, Tag

PAGE_SIZE = 20
BRAND_TAGS = {
    # Keys are model field names
    "location": [
        {"value": item[0], "display_name": item[1]}
        for item in Brand.Location.choices
    ],
    "indicative_pricing": [
        {"value": item[0], "display_name": item[1]}
        for item in Brand.IndicativePricing.choices
    ],
}


def _update_display_tags(category_tags, tag_name, tag_value, update_fields):
    for option in category_tags[tag_name]:
        if option["value"] == tag_value:
            for field in update_fields:
                option[field] = update_fields[field]


def home_page(request):
    return render(request, "index.html")


def brand_listing(request, selected_category):
    category = get_object_or_404(Category, internal_name=selected_category)

    tags = Tag.objects.filter(category__internal_name=category.internal_name)
    category_tag_names = set(tags.values_list("name", flat=True))

    # For filter options
    category_tags = dict()
    for tag in tags:
        if tag.name not in category_tags:
            category_tags[tag.name] = list()
        category_tags[tag.name].append({"value": tag.value})

    # Filter brands based on category tags provided in request params
    query_filter = None
    for tag_name in category_tag_names:
        tag_values = request.GET.getlist(tag_name)

        for tag_value in tag_values:
            if query_filter is None:
                query_filter = Q(name=tag_name, value=tag_value)
            else:
                query_filter |= Q(name=tag_name, value=tag_value)

            _update_display_tags(
                category_tags, tag_name, tag_value, {"selected": True}
            )

    if query_filter is not None:
        tags = tags.filter(query_filter)

    brands = None
    if query_filter is not None:
        # Filter brands
        brands = (
            Brand.objects.filter(brandtag__tag__in=tags)
            .annotate(match_count=Count("brandtag"))
            .filter(match_count=tags.count())
        )
    else:
        # Return all brands if no filter is applied
        brands = Brand.objects.filter(
            brandcategory__category__internal_name=category.internal_name
        )

    # Further filter brands based on brand tags provided in request params
    brand_tags = copy.deepcopy(BRAND_TAGS)
    brand_tag_names = brand_tags.keys()
    for tag_name in brand_tag_names:
        tag_values = request.GET.getlist(tag_name)

        query_filter = None
        for tag_value in tag_values:
            if query_filter is None:
                query_filter = Q(**{f"{tag_name}": tag_value})
            else:
                query_filter |= Q(**{f"{tag_name}": tag_value})

            _update_display_tags(
                brand_tags, tag_name, tag_value, {"selected": True}
            )

        if query_filter is not None:
            brands = brands.filter(query_filter)

    paginator = Paginator(brands, PAGE_SIZE)
    page_number = request.GET.get("page", 0)
    page = paginator.get_page(page_number)

    return render(
        request,
        "brand-listing.html",
        {
            "selected_category": category,
            "brands": page,
            "total_brands": len(brands),
            "category_tags": category_tags,
            "brand_tags": brand_tags,
        },
    )


def brand_detail(request, brand_id):
    brand = get_object_or_404(Brand, id=brand_id)
    return render(request, "brand-detail.html", {"brand": brand})

brand/templates/brand-categories.html
<div class="container-items">
    <a class="container-item {% if category.internal_name == 'clothing' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'clothing' %}">
        <i class="icon-cloth-1"></i>
        <div class="label">
            Clothing
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'footwear' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'footwear' %}">
        <i class="icon-footwear"></i>
        <div class="label">
            Footwear
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'handbags' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'handbags' %}">
        <i class="icon-handbags"></i>
        <div class="label">
            Handbags
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'jewellery' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'jewellery' %}">
        <i class="icon-jewellery"></i>
        <div class="label">
            Jewellery
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'wellness' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'wellness' %}">
        <i class="icon-handbags"></i>
        <div class="label">
            Beauty
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'gifting' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'gifting' %}">
        <i class="icon-gifting"></i>
        <div class="label">
            Gifting
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'food' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'food' %}">
        <i class="icon-health"></i>
        <div class="label">
            Health
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'pets' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'pets' %}">
        <i class="icon-pet"></i>
        <div class="label">
            Pet Supplies
        </div>
    </a>
    <a class="container-item {% if category.internal_name == 'kids' %}container-item-selected{% endif %}" href="{% url 'brand:brand_listing' 'kids' %}">
        <i class="icon-health"></i>
        <div class="label">
            Kids
        </div>
    </a>
</div>

brand/templates/brand-categories2.html
<div class="container">
    <br><br><br>
    <div class="category">

        <a class="text-decoration-none" href="#">
            <div class="active2">
                <p>
                    <i class="icon-cloth-1" style="font-size: 20px;"></i>&nbsp;
                    Clothing
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-footwear" style="font-size: 20px;"></i>&nbsp;
                    Footwear
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-handbags" style="font-size: 20px;"></i>&nbsp;
                    Handbags
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-jewellery" style="font-size: 20px;"></i>&nbsp;
                    Jewellery
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-handbags" style="font-size: 20px;"></i>&nbsp;
                    Beauty
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-gifting" style="font-size: 20px;"></i>&nbsp;
                    Gifting
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-health" style="font-size: 20px;"></i>&nbsp;
                    Health
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-pet" style="font-size: 20px;"></i>&nbsp;
                    Pet Supplies
                </p>
            </div>
        </a>
        <a class="text-decoration-none" href="#">
            <div class="para">
                <p>
                    <i class="icon-health" style="font-size: 20px;"></i>&nbsp;
                    Kids
                </p>
            </div>
        </a>
    </div>
</div>

brand/templates/brand-filter.html
{% load static %}
{% load get from brand_tags %}
<div class="container-filters hide-on-mobile">
    <a class="go-back">Back</a>
    <div class="filter-text hide-on-mobile">Filter Brands by <span class="primary margin-left-32">Reset</span></div>
    <button class="filter-tag border-color-unset flex align-center margin-bottom-8">Women<span
            class="margin-left-10" style="color:#E16300">x</span></button>

    <div class="margin-right-24">

        <!-- Identity -->
        {% if "identity" in category_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item">
                <div class="width-30">
                    <div
                        class="flex justify-content-center align-center filter-picture flex-column width-90 background-grey margin-8">
                        <img class="border-radius-50" src="{% static 'img/men.png' %}" alt="Men">
                        <img class="border-radius-50" src="{% static 'img/women.png' %}" alt="Women">
                    </div>
                </div>
                <div class="margin-left-14">
                    <div class="margin-bottom-8">
                        Identity <br />
                    </div>
                    <div class="flex flex-column">
                        {% for option in category_tags|get:'identity' %}
                        <div class="flex">
                            <input type="radio" id="identity-{{ forloop.counter }}" name="identity" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                            <label for="identity-{{ forloop.counter }}">{{ option|get:'value'|title }}</label> <br />
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Location -->
        {% if "location" in brand_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item">
                <div class="filter-picture width-40 flex">
                    <img src="{% static 'img/india-1.png' %}" alt="India-1">
                    <img src="{% static 'img/india-2.png' %}" alt="India-2">
                </div>
                <div>
                    Location <br />
                    {% for option in brand_tags|get:'location' %}
                    <div class="flex">
                        <input type="radio" id="location-{{ forloop.counter }}" name="location" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                        <label for="location-{{ forloop.counter }}">{{ option|get:'display_name'|title }}</label> <br />
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Price Range -->
        {% if "indicative_pricing" in brand_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item">
                <div class="width-30">
                    <div class="flex flex-column filter-picture flex justify-content-center align-center filter-picture flex-column width-90 background-grey margin-8">
                        <img class="contrast-image" src="{% static 'img/price-1.png' %}" alt="price_1">
                        <img class="contrast-image" src="{% static 'img/price-2.png' %}" alt="price_2">
                        <img class="contrast-image" src="{% static 'img/price-3.png' %}" alt="price_3">
                    </div>
                </div>
                <div class="margin-left-14">
                    <div class="margin-bottom-8">
                        Price Range <br />
                    </div>
                    {% for option in brand_tags|get:'indicative_pricing' %}
                    <label>
                        <input type="checkbox" name="indicative_pricing" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                        {{ option|get:'display_name'|title }}
                    </label>
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Occasion -->
        {% if "occasion" in category_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item">
                <div class="width-30">
                    <div class="flex flex-column filter-picture flex justify-content-center align-center filter-picture flex-column width-90 background-grey margin-8">
                        <img src="{% static 'img/occasion.png' %}" alt="occasion">
                    </div>

                </div>
                <div class="margin-left-14">
                    <div class="margin-bottom-8">
                        Occasion <br />
                    </div>
                    {% for option in category_tags|get:'occasion' %}
                    <label>
                        <input type="checkbox" name="occasion" value="{{ option|get:'value' }}" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                        {{ option|get:'value'|title }}
                    </label>
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Design -->
        {% if "design" in category_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item margin-top-8">
                <div>
                    <div class="margin-bottom-8">
                        <i class="icon-design margin-right-10 margin-left-10"></i>
                        Design <br />
                    </div>
                    <div class="margin-right-10 margin-left-14 margin-bottom-12">
                        {% for option in category_tags|get:'design' %}
                        <label>
                            <input type="checkbox" name="design" value="{{ option|get:'value' }}" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                            {{ option|get:'value'|title }}
                        </label>
                        <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Material -->
        {% if "material" in category_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item margin-top-8">
                <div>
                    <div class="margin-bottom-8">
                        <i class="icon-material margin-right-10 margin-left-10"></i>
                        Material <br />
                    </div>
                    <div class="margin-right-10 margin-left-14 margin-bottom-12">
                        {% for option in category_tags|get:'material' %}
                        <label>
                            <input type="checkbox" name="material" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                            {{ option|get:'value'|title }}
                        </label>
                        <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}

        <!-- Type -->
        {% if "type" in category_tags %}
        <div class="filter-option height-auto margin-bottom-16">
            <div class="flex flex-item margin-top-8">
                <div>
                    <div class="margin-bottom-8">
                        <i class="icon-type margin-right-10 margin-left-10"></i>
                        Type <br />
                    </div>
                    <div class="margin-right-10 margin-left-14 margin-bottom-12">
                        {% for option in category_tags|get:'type' %}
                        <label>
                            <input type="checkbox" name="type" value="{{ option|get:'value' }}" {% if option|get:'selected' %}checked{% endif %}>
                            {{ option|get:'value'|title }}
                        </label>
                        <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

brand/templates/brand-item.html
{% load static %}
<div class="brands-container">
    <div class="brand-img">
        <img style="width: 370px;height: 350px;" src="{{ brand.brandvisual.get_cover_url }}" alt="{{brand.name}}">
    </div>
    <div class="brand-container">
        <div class="brand-name">
            <i class="icon-brand-tag"></i>
            {{ brand.name }}
        </div>
        <div class="highlights margin-top-15">
            <div class="flex">
                <div class="brand-star flex-1 margin-right-8">
                    <div class="rating">{{brand.user_rating}}</div>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star-empty"></i>
                </div>
                <div class="brand-views flex-1 margin-right-8"><span class="roboto weight-700"
                    style="color:#FF7000">{{brand.page_views}}</span><span class="roboto weight-700"
                    style="color: #034121;"> Views</span></div>
            <div class="brand-india flex-1 margin-right-8 flex justify-content-center align-center"><span class="roboto weight-700 margin-right-2"
                    style="color:#E16300">Made</span><span class="roboto weight-700 margin-right-2"
                    style="color:#224DDC">
                    in</span><span class="roboto weight-700" style="color:#01753A"> India</span></div>
            </div>
        </div>
        <p class="brand-para">{{brand.description}}</p>

        <!-- brand tags -->
        <div>
            <div class="flex flex-wrap margin-bottom-16">

                {% if brand.environment_friendly %}
                <div class="tag-item">
                    <div class="flex align-center brand-views width-max-content">
                        <i class="icon-sustain sustainable"></i>
                        <span class="sustainable">Sustainable</span>
                    </div>
                </div>
                {% endif %}

                {% if brand.handcrafted %}
                <div class="tag-item">
                    <div class="flex align-center brand-views width-max-content">
                        <i class="icon-attractive-1 handcrafted margin-right-10"></i>
                        <span class="handcrafted">Handcrafted</span>
                    </div>
                </div>
                {% endif %}

                {% if brand.indicative_pricing == "BGT" %}
                <div class="tag-item">
                    <div class="flex align-center brand-views width-max-content">
                        <i class="icon-attractive-1 reasonable margin-right-10"></i>
                        <span class="reasonable">Reasonable</span>
                    </div>
                </div>
                {% endif %}

                {% if brand.plus_size_available %}
                <div class="tag-item">
                    <div class="flex align-center brand-views width-max-content">
                        <i class="icon-plus-size plus-size margin-right-10"></i>
                        <span class="plus-size">Plus Size Available</span>
                    </div>
                </div>
                {% endif %}

                {% if brand.customizable %}
                <div class="tag-item">
                    <div class="flex align-center brand-views width-max-content">
                        <i class="icon-attractive-1 customisable margin-right-10"></i>
                        <span class="customisable">Customisable</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        <button class="brand-btn">
            <a class="brand-text" href="{% url 'brand:brand_detail' brand.id %}">View More Details</a>
        </button>

    </div>
</div>